from app.rules.document_content.check_signatures import CheckSignaturesRule
from app.rules.document_content.check_pan_attached import CheckPanAttachedRule
from app.rules.document_content.check_effective_date import CheckEffectiveDateRule
from app.rules.document_content.check_stamp_duty import CheckStampDutyRule
from app.rules.document_content.check_witness_signatures import CheckWitnessSignaturesRule
from app.rules.document_content.check_company_letterhead import CheckCompanyLetterheadRule
from app.rules.document_content.check_contract_term import CheckContractTermRule
from app.rules.document_content.check_page_completeness import CheckPageCompletenessRule
