"""create_all_tables

Revision ID: 7d07b0bb56ec
Revises: 
Create Date: 2026-05-21 17:27:09.225200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d07b0bb56ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'ai_agent', 'system', name='actortype'), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.Enum('approved', 'rejected', 'modified_rule', 'uploaded', 'auto_approved', 'auto_rejected', 'pattern_detected', 'override', name='actiontype'), nullable=False),
    sa.Column('target_type', sa.Enum('deal', 'rule', 'checklist', 'document', name='targettype'), nullable=False),
    sa.Column('target_id', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('active', 'draft', 'deprecated', name='checkliststatus'), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('needs_review', 'auto_approved', 'auto_rejected', 'approved', 'rejected', 'stuck', name='dealstatus'), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=100), nullable=False),
    sa.Column('submitted_by_zone', sa.String(length=100), nullable=False),
    sa.Column('submitted_by_avatar_color', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('validation_score_passed', sa.Integer(), nullable=False),
    sa.Column('validation_score_total', sa.Integer(), nullable=False),
    sa.Column('critical_issues_count', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('first_pass_rate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('required_context', sa.JSON(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('action_on_fail', sa.Enum('auto_reject', 'flag_review', 'warning', name='actiononfail'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fired_count', sa.Integer(), nullable=False),
    sa.Column('avg_runtime_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('agreement', 'pan_card', 'gst_certificate', 'po', 'other', name='documenttype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'validated', 'issues_found', 'failed', name='documentstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=20), nullable=False),
    sa.Column('checklist_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='validationrunstatus'), nullable=False),
    sa.Column('total_rules', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('validation_run_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pass_', 'warning', 'fail', 'pending', 'running', name='ruleresultstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Enum('none', 'approve_anyway', 'reject_reason', 'pending_review', name='actiontaken'), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_results')
    op.drop_table('validation_runs')
    op.drop_table('documents')
    op.drop_table('rules')
    op.drop_table('deals')
    op.drop_table('checklists')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
