"""expand purchase_orders with workflow and customer approval columns

Revision ID: e12325e3d4c1
Revises: ad51afc39e4f
Create Date: 2026-05-27 12:36:59.075378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12325e3d4c1'
down_revision: Union[str, Sequence[str], None] = 'ad51afc39e4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite requires server_default for NOT NULL columns added to a table with existing rows
    op.add_column('purchase_orders', sa.Column('current_order_status', sa.Enum('DRAFT', 'PO_APPROVAL_PENDING', 'FIN_HOLD', 'FIN_APPROVED', 'DISCARDED', name='orderstatus'), nullable=False, server_default='DRAFT'))
    op.add_column('purchase_orders', sa.Column('finance_approval_by', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('finance_approval_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('approval_aging_minutes', sa.Integer(), nullable=True))
    op.add_column('purchase_orders', sa.Column('whatsapp_delivery_status', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('reminder_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('purchase_orders', sa.Column('po_rejected_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_rejection_reason', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('customer_name', sa.String(), nullable=False, server_default=''))
    op.add_column('purchase_orders', sa.Column('po_approved_by', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_approver_contact_no', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_approved_on', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_verification_link', sa.String(), nullable=True))
    op.add_column('purchase_orders', sa.Column('po_link_status', sa.Enum('APPROVED', 'ACTIVE', 'INACTIVE', name='polinkstatus'), nullable=True))
    op.drop_column('purchase_orders', 'validation_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('validation_status', sa.VARCHAR(), nullable=True))
    op.drop_column('purchase_orders', 'po_link_status')
    op.drop_column('purchase_orders', 'po_verification_link')
    op.drop_column('purchase_orders', 'po_approved_on')
    op.drop_column('purchase_orders', 'po_approver_contact_no')
    op.drop_column('purchase_orders', 'po_approved_by')
    op.drop_column('purchase_orders', 'customer_name')
    op.drop_column('purchase_orders', 'po_rejection_reason')
    op.drop_column('purchase_orders', 'po_rejected_at')
    op.drop_column('purchase_orders', 'reminder_count')
    op.drop_column('purchase_orders', 'whatsapp_delivery_status')
    op.drop_column('purchase_orders', 'approval_aging_minutes')
    op.drop_column('purchase_orders', 'finance_approval_at')
    op.drop_column('purchase_orders', 'finance_approval_by')
    op.drop_column('purchase_orders', 'current_order_status')
    # ### end Alembic commands ###
